import os
import time
import tyle as r
os.system('clear')
print(r.log)
print(r.name)
print(r.author)
print(r.lang)
print(r.log)
time.sleep(2)
print("\tChoose One")
a = str(input("Install Metasploit using Python/Bash: "))
if a == "Python" or a == "python":
    os.system('clear')
    os.system('echo "\tInstalling Metasploit using Python..."')
    time.sleep(2)
    os.system('clear')
    os.system(" echo '\tInstalling Packages...' ")
    time.sleep(2)
    os.system('apt update && apt upgrade -y')
    os.system('pkg install wget curl openssh git -y')
    os.system('pkg install python python2 -y')
    os.system('apt install ncurses-utils')
    os.system('wget https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master/metasploit.sh')
    os.system('chmod +x * metasploit.sh')
    os.system(' echo "\tInstalling msfconsole Please Be patient!!..." ')
    time.sleep(4)
    os.system('./metasploit.sh')
    os.system('clear')
    os.system(' echo "\tUsage: msfconsole" ')
    time.sleep(3)
    os.system('clear')
    print(" Thanks For Using me,See you in Heaven,,hehe Just kidding,,,Bye-Bye ")
    time.sleep(4)
    os.system('cd ..')
    os.system('rm -fr MeTasploit')
    exit()

elif a == "bash" or a == "Bash":
    os.system('touch install.sh')
    os.system('clear')
    os.system(' echo clear >> install.sh ')
    os.system(' echo " echo\tInstalling Metasploitt Using Bash Script..." > install.sh ')
    os.system(' echo "echo\tInstalling Packages..." >> install.sh ')
    os.system('echo sleep 2 >> install.sh ')
    os.system(' echo clear >> install.sh ')
    os.system(' echo pkg install wget curl openssh git  >> install.sh ')
    os.system(' echo pkg install python python2  >> install.sh ')
    os.system(' echo apt install ncurses-utils >> install.sh ')
    os.system(' echo wget https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master/metasploit.sh >> install.sh ' )
    os.system(' echo chmod +x * metasploit.sh >> install.sh ')
    os.system(' echo "echo\tInstalling msfconsole,Please Be patient!,,," >> install.sh ')
    os.system(' echo sleep 4 >> install.sh ')
    os.system(' echo ./metasploit.sh >> install.sh ')
    os.system(' echo clear >> install.sh ')
    os.system(' echo "echo\t Usage: msfconsole " >> install.sh ')
    os.system(' echo sleep 3 >> install.sh ')
    os.system(' echo clear >> install.sh ')
    os.system(' echo "echo\t Thanks For Using me,See you in Heaven,,hehe Just kidding,,,Bye-Bye" >> install.sh ')
    os.system(' echo sleep 3 >> install.sh ')
    os.system('bash install.sh')
    os.system('cd ..')
    os.system('rm -fr MeTasploit')
    exit()
else:
    print("\tTRY AGAIN!")
